export const queryKeys = {
  scholarDashboard: ["scholar", "dashboard"] as const,
  scholarAssignments: (filters?: Record<string, unknown>) =>
    filters ? (["scholar", "assignments", filters] as const) : (["scholar", "assignments"] as const),
  scholarCourses: ["scholar", "courses"] as const,
  scholarResources: (filters?: Record<string, unknown>) =>
    filters ? (["scholar", "resources", filters] as const) : (["scholar", "resources"] as const),
  scholarCohort: ["scholar", "cohort"] as const,
  userProfile: ["user", "profile"] as const,
  conversations: ["chats", "conversations"] as const,
  messages: (conversationId: string) =>
    ["chats", "messages", conversationId] as const,
  mentorScholars: ["mentor", "scholars"] as const,
  mentorScholar: (id: string) => ["mentor", "scholars", id] as const,
  mentorAssignments: ["mentor", "assignments"] as const,
  verificationQueue: ["mentor", "verification"] as const,
  mentorMeetings: ["mentor", "meetings"] as const,
  mentorCourses: ["mentor", "courses"] as const,
  mentorResources: ["mentor", "resources"] as const,
  mentorProfile: ["mentor", "profile"] as const,
  adminDashboard: ["admin", "dashboard"] as const,
  programs: ["admin", "programs"] as const,
  program: (id: string) => ["admin", "programs", id] as const,
  adminCourses: ["admin", "courses"] as const,
  adminScholars: ["admin", "scholars"] as const,
  adminScholar: (id: string) => ["admin", "scholars", id] as const,
  adminMentors: ["admin", "mentors"] as const,
  adminMentor: (id: string) => ["admin", "mentors", id] as const,
  adminAssignments: ["admin", "assignments"] as const,
  adminAssignment: (id: string) => ["admin", "assignments", id] as const,
  adminVerificationQueue: ["admin", "verification"] as const,
  submission: (assignmentId: string, submissionId: string) =>
    ["admin", "submissions", assignmentId, submissionId] as const,
  adminMeetings: ["admin", "meetings"] as const,
  attendanceOverview: ["admin", "attendance"] as const,
  attendanceRoster: (meetingId: string) =>
    ["admin", "attendance", meetingId] as const,
  attendanceHistory: (meetingId: string) =>
    ["admin", "attendance", meetingId, "history"] as const,
  invitations: ["admin", "invitations"] as const,
  importJob: (jobId: string) => ["admin", "import", jobId] as const,
  reports: ["admin", "reports"] as const,
  report: (reportId: string) => ["admin", "reports", reportId] as const,
  orgSettings: ["admin", "settings"] as const,
  auditLogs: ["admin", "audit"] as const,
};
